### PR TITLE
add the possibility to modify the public folder

### PR DESCRIPTION
**Pull request by maamri95**
i got issue when i tried change public directory, i propose add to possibility change it in config/packages/pentatrion_vite.yaml by public_dir variable.

PS: my english is bad so i don't know if my comment is explicit enough in the readme

### CODE REVIEW

**Comment by lhapaipai** [comment]
Hi @maamri95,
Thank you for your PR.
Of course, it's a bad idea to hard code the `public` directory.

However, I think it would be easier to use the parameter `kernel.web_root` and not to add a config option that you could guess with other kernel parameters ?

from `src/Resources/config/services.xml` :
```diff
    <service id="vite.entrypoints_lookup" class="Pentatrion\ViteBundle\Asset\EntrypointsLookup">
-      <argument>%kernel.project_dir%/public%pentatrion_vite.base%entrypoints.json</argument>
+      <argument>%kernel.web_root%%pentatrion_vite.base%entrypoints.json</argument>
    </service>
``` 

what do you think about that ?

**Comment by maamri95** [comment]
Hi @thapaipai thanks for your answer, yes if it is possible to guess with other kernel parameters it will be more efficient,
but i tried your suggestion and it doesn't worked for me i don't have variable named web_root in my kernel, my symfony project is on php 7.4 and i haven't found an answer to that, thanks for me send one if you have one.

**Comment by lhapaipai** [comment]
Your totally right, I was the one who had defined this parameter in one of my projects, sorry :dizzy_face:
I'm okay with your pr except the line 29 in `src/Resources/config/services.xml`

The ViteController constructor have only 3 parameters

```php
//src/Controller/ViteController.php
class ViteController
{
    public $viteDevServer;
    public $httpClient;

    public function __construct($viteDevServer, $viteBase, HttpClientInterface $httpClient)
    {
        $this->viteDevServer = $viteDevServer;
        $this->viteBase = $viteBase;
        $this->httpClient = $httpClient;
    }
    // ...
}
```
what did you think about this? did you forget to put this file in your pull request ?

this controller is used to relay http requests to the vite dev server such as assets or pings like `https://127.0.0.1:8000/build/__vite_ping`.

**Comment by maamri95** [comment]
it is not necessary in ViewController because we not need modify url i think, because that manage by dev server of rellup(vitejs), but for me dev server don't work, that ping no stop (before my pull request)

**Comment by lhapaipai** [comment]
thank you it's merged !

**Comment by maamri95** [comment]
you welcome, and for dev server if you can explain me how fix my problem (ping no stop) i use a js vanilla

**Comment by lhapaipai** [comment]
I'm not really sure I understood your question correctly.

check that you have correctly set the vite route file :
```yaml
# config/routes/dev/pentatrion_vite.yaml
_pentatrion_vite:
    prefix: /build
    resource: "@PentatrionViteBundle/Resources/config/routing.yaml"
```

start your symfony local server
```console
symfony serve --no-tls --document-root=<your-custom-dir>
```
in another console
```console
npm run dev
```

what's your result if you browse `http://127.0.0.1:8000/build/__vite_ping`

**Comment by maamri95** [comment]
thank you

**Pull request merged**
